# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategories',
            name='ict_valid',
            field=models.BooleanField(default=True),
        ),
    ]
