# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app_rest', '0002_imagecategories_ict_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategories',
            name='ict_last_taken',
            field=models.BigIntegerField(default=-1),
        ),
    ]
