# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app_rest', '0003_imagecategories_ict_last_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecategories',
            name='ict_last_taken',
        ),
    ]
