# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app_rest', '0004_remove_imagecategories_ict_last_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecategories',
            name='ict_taken_for_labeling',
            field=models.BooleanField(default=False),
        ),
    ]
