# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='bbx_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
