# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicalTurkCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtc_code', models.CharField(max_length=200)),
                ('mtc_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uim_image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_app.ImageCategories')),
                ('uim_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userspecifics',
            name='usr_is_mechanical_turk',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userspecifics',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to=settings.AUTH_USER_MODEL),
        ),
    ]
