# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_app', '0003_auto_20170208_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_app.ImageCategories')),
                ('uci_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
