# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app', '0007_auto_20170210_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='uim_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
