# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_app', '0008_userimages_uim_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='bbx_image_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='bbx_image_width',
            field=models.FloatField(default=0.0),
        ),
    ]
